### ISSUE TITLE
getting Error

### ISSUE THREAD

**Issue by shivamwane** [iankuoli/DFNet_TF2#7]
NotFoundError: /root/Dataset/celeba/train_imgs_tiny; No such file or directory [Op:MatchingFiles]
while running task.py 
how to change the directory path

**Comment by shivamwane** [comment]
above problem solved

**Comment by shivamwane** [comment]
Loading Data from datasets_path/celeba_train_local.flist ......
  0% 0/162770 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "task.py", line 45, in <module>
    is_url=config.is_url)
  File "/content/DFNet_TF2/trainer/datasets.py", line 82, in load_from_flist
    img = cv2.resize(read(line, is_url), output_wh, interpolation=cv2.INTER_LINEAR)
  File "/content/DFNet_TF2/trainer/datasets.py", line 77, in read
    return cv2.imread(os.path.expanduser(line.strip())).astype(np.float32)
AttributeError: 'NoneType' object has no attribute 'astype'

**Comment by styler00dollar** [comment]
It seems like you didn't load valid data. Either corrupt files or you have wrong image paths inside ```celeba_train_local.flist```. Your flist should look like this
```
/path/image.png
/path/image2.png
....
```
Note that there are no empty lines allowed.

**Comment by iankuoli** [comment]
image path in `celeba_train_local.flist` should be listed correctly.
```
/path/image1.png
/path/image2.png
....
```
